In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.python.framework import ops

In [10]:
a = np.array([[1],[2],[3]])
b = np.array([[1,2],[2,3]])
print (a)
print (b)

[[1]
 [2]
 [3]]
[[1 2]
 [2 3]]


In [11]:
a.shape
b.shape

(2, 2)

In [13]:
np.squeeze(a)
b=np.squeeze(b)
b.shape

(2, 2)

In [4]:
%%time
a=5
b=5
print (a+b)

10
Wall time: 1 ms


In [2]:
import numpy as np
a= np.array([[5],[2]])
(a).T.shape

(1, 2)

In [47]:
ops.reset_default_graph() 
layer = [2,3,4]
parameter={}
for i,v in enumerate(layer):
    parameter['b' + str(i+1)] =tf.get_variable('b' + str(i+1), [layer[i], 1], initializer = tf.zeros_initializer()) 
    parameter['W' + str(i+1)] =tf.get_variable('W' + str(i+1), [layer[i], layer[i-1]], initializer = tf.contrib.layers.xavier_initializer(seed = 1))

print (parameter)    

{'b1': <tf.Variable 'b1:0' shape=(2, 1) dtype=float32_ref>, 'W1': <tf.Variable 'W1:0' shape=(2, 4) dtype=float32_ref>, 'b2': <tf.Variable 'b2:0' shape=(3, 1) dtype=float32_ref>, 'W2': <tf.Variable 'W2:0' shape=(3, 2) dtype=float32_ref>, 'b3': <tf.Variable 'b3:0' shape=(4, 1) dtype=float32_ref>, 'W3': <tf.Variable 'W3:0' shape=(4, 3) dtype=float32_ref>}


In [51]:
max= (len(parameter))
for i,v in enumerate(parameter):
    if (i==max-1):
        break
    print (parameter[v])
    print (parameter[v])
    i=i+1

print ("---")
print (parameter[v])

<tf.Variable 'b1:0' shape=(2, 1) dtype=float32_ref>
<tf.Variable 'b1:0' shape=(2, 1) dtype=float32_ref>
<tf.Variable 'W1:0' shape=(2, 4) dtype=float32_ref>
<tf.Variable 'W1:0' shape=(2, 4) dtype=float32_ref>
<tf.Variable 'b2:0' shape=(3, 1) dtype=float32_ref>
<tf.Variable 'b2:0' shape=(3, 1) dtype=float32_ref>
<tf.Variable 'W2:0' shape=(3, 2) dtype=float32_ref>
<tf.Variable 'W2:0' shape=(3, 2) dtype=float32_ref>
<tf.Variable 'b3:0' shape=(4, 1) dtype=float32_ref>
<tf.Variable 'b3:0' shape=(4, 1) dtype=float32_ref>
---
<tf.Variable 'W3:0' shape=(4, 3) dtype=float32_ref>


In [72]:
maximo= (len(parameter))
print(maximo)
print ("----")
cont =1
for i in range(1,maximo+1,2):
    print (i)
    print ((maximo)/2)
    if (cont==((maximo)/2)):
        break
    print (parameter['W'+str(cont)])
    cont=cont+1


print ("---")
print (parameter['W'+str(cont)])

6
----
1
3.0
<tf.Variable 'W1:0' shape=(2, 4) dtype=float32_ref>
3
3.0
<tf.Variable 'W2:0' shape=(3, 2) dtype=float32_ref>
5
3.0
---
<tf.Variable 'W3:0' shape=(4, 3) dtype=float32_ref>


In [6]:
import time
result=['uno','dos']
fecha=time.strftime("%d-%m-%Y-%H-%M-%S")
resultado = '\n'.join(map(str, result))

f = open ('archivo'+fecha+'.txt',"w")
f.write(resultado)
f.close()
print("----Termino-----")

----Termino-----


In [38]:
np.random.seed(1)
l_el= -4*np.random.rand(30)
print(l_el)
np.unique(np.around(np.power(10,l_el),decimals=5))

[ -1.66808802e+00  -2.88129797e+00  -4.57499269e-04  -1.20933029e+00
  -5.87023563e-01  -3.69354379e-01  -7.45040846e-01  -1.38224291e+00
  -1.58706990e+00  -2.15526694e+00  -1.67677806e+00  -2.74087800e+00
  -8.17808999e-01  -3.51246975e+00  -1.09550373e-01  -2.68187004e+00
  -1.66921921e+00  -2.23475931e+00  -5.61547754e-01  -7.92405956e-01
  -3.20297827e+00  -3.87304630e+00  -1.25369671e+00  -2.76929046e+00
  -3.50555661e+00  -3.57842665e+00  -3.40176845e-01  -1.56219133e-01
  -6.79321678e-01  -3.51257001e+00]


array([  1.30000000e-04,   2.60000000e-04,   3.10000000e-04,
         6.30000000e-04,   1.31000000e-03,   1.70000000e-03,
         1.82000000e-03,   2.08000000e-03,   5.82000000e-03,
         6.99000000e-03,   2.10500000e-02,   2.14200000e-02,
         2.14700000e-02,   2.58800000e-02,   4.14700000e-02,
         5.57600000e-02,   6.17500000e-02,   1.52120000e-01,
         1.61290000e-01,   1.79870000e-01,   2.09260000e-01,
         2.58810000e-01,   2.74440000e-01,   4.27210000e-01,
         4.56900000e-01,   6.97880000e-01,   7.77050000e-01,
         9.98950000e-01])

In [6]:
10

hola


In [26]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import MinMaxScaler

X_train_p=np.array([100.0,200.0,300.0,1000,0])
scaler= MinMaxScaler()
scaler.fit(X_train_p)
    
X_train_p = scaler.transform(X_train_p)
print (X_train_p)

[ 0.1  0.2  0.3  1.   0. ]


In [42]:
r=np.random.rand(5)
beta = r*0.09 +0.9
print (beta)

[ 0.94798488  0.96226894  0.92839641  0.96178508  0.97511631]


In [45]:
r=np.random.rand(5)
print (r)
beta =1-10**(-r-1)
print (beta)

[ 0.28777534  0.13002857  0.01936696  0.67883553  0.21162812]
[ 0.94845048  0.92587385  0.90436144  0.97905094  0.93857122]


In [52]:
l_el = np.random.uniform(-4,-2,10)
print (np.unique(np.around(np.power(10,l_el),decimals=5)))

[ 0.00017  0.00035  0.0005   0.00072  0.00079  0.00175  0.00212  0.00619
  0.00792  0.00851]


In [53]:
a = np.array([[1,2],[1,2]])

In [55]:
a.T

array([[1, 1],
       [2, 2]])

In [56]:
np.matmul(a,a.T)

array([[5, 5],
       [5, 5]])

In [58]:
np.dot(a,a.T)

array([[5, 5],
       [5, 5]])

In [59]:
from sklearn.decomposition import TruncatedSVD

In [60]:
import numpy as np
LA = np.linalg


In [61]:
a = np.array([[1,1,1,0,0],[3,3,3,0,0],[4,4,4,0,0],[5,5,5,0,0],[0,2,0,4,4],[0,0,0,5,5],[0,1,0,2,2]])

In [93]:
U, s, V = np.linalg.svd(a, full_matrices=False)

In [94]:
a.shape

(7, 5)

In [98]:
np.set_printoptions(suppress=True)
np.set_printoptions(precision=3)
print(U)
print ("----")
print(s)
print ("*********")
print (V)

[[-0.138  0.024  0.011  0.99  -0.   ]
 [-0.413  0.071  0.032 -0.059 -0.885]
 [-0.55   0.094  0.043 -0.079  0.424]
 [-0.688  0.118  0.054 -0.099  0.192]
 [-0.153 -0.591 -0.654 -0.     0.   ]
 [-0.072 -0.731  0.678  0.    -0.   ]
 [-0.076 -0.296 -0.327 -0.    -0.   ]]
----
[ 12.481   9.509   1.346   0.      0.   ]
*********
[[-0.562 -0.593 -0.562 -0.09  -0.09 ]
 [ 0.127 -0.029  0.127 -0.695 -0.695]
 [ 0.41  -0.805  0.41   0.091  0.091]
 [-0.707  0.     0.707 -0.     0.   ]
 [-0.     0.    -0.     0.707 -0.707]]


In [80]:
import numpy as np
import scipy.linalg as SL
a = np.array([[1,1,1,0,0],[3,3,3,0,0],[4,4,4,0,0],[5,5,5,0,0],[0,2,0,4,4],[0,0,0,5,5],[0,1,0,2,2]])

U, s, Vh = SL.svd(a, full_matrices=False)

print (U)

[[-0.138  0.024  0.011  0.99  -0.   ]
 [-0.413  0.071  0.032 -0.059 -0.885]
 [-0.55   0.094  0.043 -0.079  0.424]
 [-0.688  0.118  0.054 -0.099  0.192]
 [-0.153 -0.591 -0.654 -0.     0.   ]
 [-0.072 -0.731  0.678  0.    -0.   ]
 [-0.076 -0.296 -0.327 -0.    -0.   ]]
