In [1]:
import math
import numpy as np
import h5py
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.python.framework import ops

%matplotlib inline
np.random.seed(1)

In [2]:
#session = tf.InteractiveSession()
y_hat = tf.constant(36,name='y_hat')
y=tf.constant(39,name='y')

# se crea la variable que es una ecuación
loss = tf.Variable((y-y_hat)**2)
# se inicializa la variable
init = tf.global_variables_initializer()

#print (y.eval())
#print (y_hat.eval())

# se crea la sesión
with tf.Session() as session:
    #se inicializan las variables y se ejecutan
    session.run(init)
    #print la loss
    print (session.run(loss))
    

9


In [3]:
a = tf.constant(2)
b = tf.constant(3)
c = tf.multiply(a,b)
d =tf.Variable(a*b)
init = tf.global_variables_initializer()

with tf.Session() as session:
    print (session.run(a))
    print (c)
    print (session.run(c))
    
    session.run(init)
    print (d)
    print (session.run(d))


2
Tensor("Mul:0", shape=(), dtype=int32)
6
<tf.Variable 'Variable_1:0' shape=() dtype=int32_ref>
6


In [4]:
x1 = tf.placeholder(tf.int64, name="x")
with tf.Session() as session:
    print (session.run(2*x1, feed_dict={x1:4}))

8


### Linear

In [5]:
def linear_function():
    np.random.seed(2)
    
    W = tf.constant(np.random.randn(4,3),name="W")
    X = tf.constant(np.random.randn(3,1),name="X")
    b = tf.constant(np.random.randn(4,1),name="b")
    
    # Y = WX + b
    Y = tf.add(tf.matmul(W,X),b)
    
    with tf.Session() as session:
        result = session.run(Y)
    
    session.close()
    
    return result

In [6]:
print (linear_function())

[[-1.70210373]
 [ 1.60018171]
 [ 2.0177319 ]
 [-0.16648128]]


In [7]:
def sigmoid(z):
    x = tf.placeholder(tf.float32,name="x")
    
    sigmoid = tf.sigmoid(x)
    
    with tf.Session() as session:
        result = session.run(sigmoid, feed_dict={x:z})
        
    return result

In [8]:
print ("0 " + str(sigmoid(0)))
print ("12 " + str(sigmoid(12)))

0 0.5
12 0.999994


In [9]:
def cost(logits,labels):
    z=tf.placeholder(tf.float32,name='z')
    y=tf.placeholder(tf.float32,name="y")
    
    cost = tf.nn.sigmoid_cross_entropy_with_logits(logits=z, labels=y)
    
    with tf.Session() as session:
        cost = session.run(cost, feed_dict={z:logits , y:labels})
    
    return cost

In [10]:
logits = sigmoid(np.array([0.2, 0.4, 0.7, 0.9]))
logits = logits.reshape(1,4)

logits_1 = np.array([0.2, 0.4, 0.7, 0.9])
logits_1 = logits.reshape(1,4)

y= np.array([0,0,1,1]).reshape(1,4)

aux = sigmoid(np.array([logits]))
#[0.2, 0.4, 0.7, 0.9]
#print ("logits = " + str(logits))
#print ("aux =" + str(aux))
#[0,0,1,1]
cost1 = cost(logits_1,y )
print ("suma costo " + str(cost1.sum(axis = 1)))
print ("cost = " + str(cost1))

suma costo [ 2.85544848]
cost = [[ 1.00538719  1.03664076  0.41385433  0.39956617]]


In [11]:
def compute_cost(a3, Y):
    
    """
    Implement the cost function
    
    Arguments:
    a3 -- post-activation, output of forward propagation
    Y -- "true" labels vector, same shape as a3
    
    Returns:
    cost - value of the cost function
    """
    m = Y.shape[1]
    #print (m)
    logprobs = np.multiply(-np.log(a3),Y) + np.multiply(-np.log(1 - a3), 1 - Y)
    #cost = 1./m * np.sum(logprobs)
    #cost = 0
    return logprobs

In [12]:
cost1 = compute_cost(logits,y)
print (cost1)

[[ 0.7981388   0.91301525  0.40318611  0.34115392]]


In [13]:
logits.shape

(1, 4)

In [16]:
def one_hot_matrix(labels,C):
    c=tf.constant(C,name="C")
    one_hot_matrix = tf.one_hot(indices=labels, depth=C, axis=0)
    with tf.Session() as session:
        one_hot = session.run(one_hot_matrix)
        session.close()
    
    return one_hot

In [17]:
labels = np.array([1,2,3,0,2,1])
one_hot = one_hot_matrix(labels, 4)
print ("one_hot = " + str(one_hot))

one_hot = [[ 0.  0.  0.  1.  0.  0.]
 [ 1.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.  0.]]


In [18]:
def ones(shape):
    ones = tf.ones(shape)
    with tf.Session() as session:
        ones = session.run(ones)
    return ones

In [19]:
print ("ones = " + str(ones([3,3])))

ones = [[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [20]:
from ejemplos.tensorflow.tf_utils import load_dataset, random_mini_batches, convert_to_one_hot, predict

In [44]:
X_train_orig, Y_train_orig, X_test_orig, Y_test_orig, classes = load_dataset('C:/Users/daniel.montjoyp/Documents/kaggle/ejemplos/tensorflow/')

hola


In [41]:
X_train_orig.shape
print (str(X_train_orig[1][1]))

[[237 232 223]
 [238 232 223]
 [238 232 223]
 [237 231 222]
 [237 231 222]
 [237 231 223]
 [236 230 223]
 [236 230 222]
 [236 230 222]
 [236 230 222]
 [236 231 222]
 [236 230 223]
 [236 230 223]
 [236 230 223]
 [235 230 222]
 [235 229 221]
 [235 229 222]
 [236 230 222]
 [234 229 221]
 [235 229 222]
 [234 229 222]
 [234 228 221]
 [233 228 220]
 [233 228 221]
 [233 228 221]
 [233 227 220]
 [233 227 220]
 [233 227 220]
 [233 227 220]
 [232 227 219]
 [232 226 219]
 [232 226 218]
 [232 225 217]
 [231 225 216]
 [230 224 216]
 [230 224 216]
 [230 224 216]
 [229 224 215]
 [229 223 215]
 [228 222 215]
 [228 222 215]
 [227 221 214]
 [226 221 213]
 [226 220 213]
 [226 220 213]
 [226 219 212]
 [225 219 212]
 [225 218 211]
 [224 218 210]
 [224 218 210]
 [223 217 209]
 [222 216 209]
 [223 216 209]
 [223 216 209]
 [223 216 208]
 [223 216 208]
 [223 216 207]
 [222 216 207]
 [221 216 207]
 [222 215 207]
 [222 216 208]
 [222 216 209]
 [222 216 208]
 [223 217 207]]


In [47]:
X_train_flatten = X_train_orig.reshape(X_train_orig.shape[0],-1).T
X_test_flatten = X_test_orig.reshape(X_test_orig.shape[0],-1).T

In [48]:
X_train_flatten.shape

(12288, 1080)

In [49]:
X_train_flatten = X_train_flatten/255.
X_test_flatten =  X_test_flatten/255.

In [51]:
Y_train = convert_to_one_hot(Y_train_orig,6)
Y_test = convert_to_one_hot(Y_test_orig,6)

In [52]:
Y_test

array([[ 1.,  1.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,
         0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
         0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
         0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,
         1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,
         0.,  0.,  0.,  0.,

In [56]:
def create_placeholders(n_x,n_y):
    
    X= tf.placeholder(tf.float32, shape=(n_x,none),name="X")
    Y= tf.placeholder(tf.float32, shape=(n_y,none),name="Y")
    
    return X,Y

In [57]:
def initialize_parameters():
    tf.set_random_seed(1)
    
    W1 = tf.get_variable("W1",[25,12288], initializer=tf.contrib.layers.xavier_initializer(seed=1))
    b1= tf.get_variable("b1",[25,1], initializer=tf.zeros_initializer())
    
    W2 = tf.get_variable("W2",[12,25], initializer=tf.contrib.layers.xavier_initializer(seed=1))
    b2= tf.get_variable("b2",[12,1], initializer=tf.zeros_initializer())
    
    W3 = tf.get_variable("W3",[6,12], initializer=tf.contrib.layers.xavier_initializer(seed=1))
    b3= tf.get_variable("b3",[6,1], initializer=tf.zeros_initializer())
    
    return parameters
