In [1]:
import numpy as np

In [5]:
a = np.array([1, 2, 3.0,-1])
b = np.array([1, 2, 3.0,-1])

In [7]:
a=np.int64(a>0)

In [8]:
np.multiply(b,a)

array([ 1.,  2.,  3., -0.])

In [9]:
np.dot(a,b)

6.0

In [19]:
x= np.array([[1, 2], [3.0,1]])
y = np.array([[1, 2],[3.0,1]])

In [20]:
np.multiply(x,y)

array([[ 1.,  4.],
       [ 9.,  1.]])

In [21]:
np.dot(x,y)

array([[ 7.,  4.],
       [ 6.,  7.]])

In [22]:
np.matmul(x,y)

array([[ 7.,  4.],
       [ 6.,  7.]])

In [23]:
np.multiply(x,y)

array([[ 1.,  4.],
       [ 9.,  1.]])